### ISSUE TITLE
Problem extracting european Metroid Zero Mission (BMXP)

### ISSUE THREAD

**Issue by Azidus** [AwakeEchidna/wiiu-vc-extractor#33]
When trying to extract Metroid Zero mission i get following error:

![screen shot 08-24-18 at 04 57 pm](https://user-images.githubusercontent.com/42677819/44593283-469dad00-a7c3-11e8-8dbf-68f705cd5a7b.PNG)

The game has been transfered to a Windows 10(64 Bit) PC using DDD, I have tried extracting a handful of other ROMs, WarioWare directly before this and Castlevania CotM directly after, and they seem to work just fine. 
This is very similar to issue #17 except that my version of the game is BMXP(which is listed in the gbaromanmed.scv file) instead of BMXE, I have tried using WiiuVCextractor ver. 0.4.1 and the "testtitlegbafix2", but they yield the exact same result....
This problem seems to be the same as issue #27 which has been closed, but I cant see what the solution was.

Thank you for an otherwise awesome program, any help is appreciated.

**Comment by wheatevo** [comment]
Comment from the no-intro DB nodes:
` Wii U EUR Virtual Console Dump. GBATA shows Start Offset as 08784000 Intro? 4 Byte change at beginning of file from retail EUR. `

**Comment by wheatevo** [comment]
@Azidus 
Please try using verbose output in the new version of Wii U VC extractor at https://github.com/wheatevo/wiiu-vc-extractor/releases/tag/0.7.0 and post the results here.

**Comment by Azidus** [comment]
Hm thats odd.. I have tried the 0.7.0 version you linked to above, it gives me the exact same result as the image I originally posted.
I can confirm that it does work with turbo-grafx games though, so thats good!

**Comment by wheatevo** [comment]
That's strange, it may not be getting to the point where it would begin outputting the more verbose output. I'll add a bit more logging for the GBA extraction to see if we can get something.

**Comment by wheatevo** [comment]
@Azidus 

New bug fix release at https://github.com/wheatevo/wiiu-vc-extractor/releases/tag/0.7.1. This one should actually get you at least a little more information before the failure. Please let me know if the output appears more verbose.

**Comment by Azidus** [comment]
OK, heres the output from version 0.7.1.
The CMD cuts off everything before:
"Checking if system/config/session_ui_search_list.psb.m contains the rom subfile path..."
I assume its because the output is too long, let me know how I can save the unabridged version if need be.
It stops at:
"Checking if system/sound/se.psb contains the rom subfile path..."
before trying to decompress the rom and failing in the same fashion as before.

It should be said that for the last couple of days, I have only been testing the program with the "alldata.psb.m" and"alldata.bin" files, are any other files dumped via DDD neccessary?
[BMXP rapport.txt](https://github.com/wheatevo/wiiu-vc-extractor/files/3422870/BMXP.rapport.txt)

**Comment by wheatevo** [comment]
Thanks, that helps. You should only need those two files for the extraction.
