### ISSUE TITLE
New alldata.psb.m format/compression

### ISSUE THREAD

**Issue by buggii** [AwakeEchidna/wiiu-vc-extractor#42]
In Sega Ages (Switch titles) roms are inside the alldata.bin file but the .psb.m is not recognized by your great tool. The error is:

"Could not succesfully read PSB file: Bad state (unknown compression method (0xFC))"

Here they are the tested files: https://mega.nz/#!rkEjxYgQ!yxhMT_tedk-EWjY-mHsMMI7Viw_Keynl4O_9ZoUoHfA

Is it possible for you to add this format too ? Thank you in advance !

EDIT:
unpack-psb.py seems to work using the fixed seed found inside the "main" executable (emulator) of the Sega Ages games so yeah, your tool is already able to decrypt, just "adjust" the fixed seed :)

**Comment by ticky** [comment]
@buggii I don’t suppose you'd have more context on how to retrieve the seeds? I’m trying to accomplish the same task.

**Comment by buggii** [comment]
The fixed seed for those games is:

25G/xpvTbsb+6

**Comment by ticky** [comment]
Thank you! 😃
