### ISSUE TITLE
Support for combining .rom and .pcm files?

### ISSUE THREAD

**Issue by CountHomer69** [AwakeEchidna/wiiu-vc-extractor#46]
I figured it would be a good idea to suggest adding support for combining .rom and .pcm files, which may be created rather than skipping the step and forming a real .sfc (when someone uses another converter). This happens when extracting an SFROM with another program, and is most common with SNES Classic and regular Wii VC, and plenty of people use WiiU VC Extractor for both mentioned platforms (maybe some using for Switch). At the moment, there is only one program that does so (snesrestore from vcromclaim), which currently cannot be run, due to Python upgrading and disabling any program/code required to run 2.7 and below. People need a good alternative, and I think this will help me out, as well as make a good addition to the tool. Thanks for reading.

**Comment by AwakeEchidna** [comment]
Out of scope.
