### ISSUE TITLE
[Enhancement] Support for Smash Bros for Wii U Masterpieces

### ISSUE THREAD

**Issue by Tcm0** [AwakeEchidna/wiiu-vc-extractor#58]
Smash Bros for Wii U contains some Gameboy, NES and SNES ROMs for the masterpieces collection. The rom files can be extracted with sm4shexplorer but only gameboy roms can be used directly. The other roms are in a .bin format that can't be played by an emulator.

**Comment by AwakeEchidna** [comment]
Out of scope.
